# -*- coding: utf-8 -*-
"""Password Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWX07fhihwmfSUGvKFNWgmPhKQL0F9jg
"""

import random
import string

def generate_password(length, use_upper, use_digits, use_symbols):
    characters = string.ascii_lowercase
    if use_upper:
        characters += string.ascii_uppercase
    if use_digits:
        characters += string.digits
    if use_symbols:
        characters += string.punctuation

    password = "".join(random.choice(characters) for _ in range(length))
    return password

def check_strength(length, use_upper, use_digits, use_symbols):
    score = sum([length >= 12, use_upper, use_digits, use_symbols])
    if score == 4:
        return "💪 Strong"
    elif score == 3:
        return "👍 Medium"
    else:
        return "⚠️ Weak"

def main():
    print("=" * 40)
    print("     🔐 Password Generator")
    print("=" * 40)

    while True:
        length = 0
        while length < 6 or length > 32:
            try:
                length = int(input("\nEnter password length (6-32): "))
                if length < 6 or length > 32:
                    print(" Please enter a number between 6 and 32.")
            except ValueError:
                print(" Please enter a valid number.")
                length = 0
        use_upper   = input("Include UPPERCASE letters? (yes/no): ").strip().lower() == "yes"
        use_digits  = input("Include NUMBERS? (yes/no): ").strip().lower() == "yes"
        use_symbols = input("Include SYMBOLS (!@#$)? (yes/no): ").strip().lower() == "yes"
        count = 1
        try:
            count = int(input("How many passwords to generate? (1-10): "))
            count = max(1, min(count, 10))
        except ValueError:
            count = 1
        print("\n" + "=" * 40)
        print("       ✅ Your Generated Passwords")
        print("=" * 40)
        for i in range(count):
            pwd = generate_password(length, use_upper, use_digits, use_symbols)
            strength = check_strength(length, use_upper, use_digits, use_symbols)
            print(f"{i+1}. {pwd}  [{strength}]")
        print("=" * 40)
        again = input("\n Generate more passwords? (yes/no): ").strip().lower()
        if again == "yes":
            print("\n")
        else:
            print("\nStay safe online! Goodbye! 👋")
            break

main()

